### ISSUE TITLE
Error when deploying to heroku

### ISSUE THREAD

**Issue by andreaspapav** [samirelanduk/samireland.com#6]
For some reason, I get this error when deployed on Heroku.

Request Method: | GET
-- | --
https://papasport.herokuapp.com/
2.2.6
ProgrammingError at /
relation "publications" does not exist LINE 1: ..."publications"."image", "publications"."pdf" FROM "publicati...                                                              ^
/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 84
/app/.heroku/python/bin/python
3.6.9
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python36.zip',  '/app/.heroku/python/lib/python3.6',  '/app/.heroku/python/lib/python3.6/lib-dynload',  '/app/.heroku/python/lib/python3.6/site-packages']
Sat, 26 Oct 2019 03:09:35 +0000

**Comment by samirelanduk** [comment]
I haven't used heroku before so I'm not sure exactly how deployment with it works, but the error message you got suggests that the database hasn't been created, which you usually do with:

    python manage.py migrate
